# Generated by Django 5.1.6 on 2025-04-02 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(blank=True, choices=[('male', 'Hombre'), ('female', 'Mujer')], max_length=10, null=True)),
                ('objetivo', models.CharField(blank=True, choices=[('lose_weight', 'Bajar de peso'), ('improve_health', 'Mejorar salud'), ('gain_weight', 'Subir de peso')], max_length=20, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('nivel_actividad', models.CharField(blank=True, choices=[('sedentario', 'Sedentario'), ('ligero', 'Ligero'), ('moderado', 'Moderado'), ('activo', 'Activo'), ('muy_activo', 'Muy Activo')], max_length=15, null=True)),
                ('presupuesto', models.FloatField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
