# Generated by Django 5.1.6 on 2025-04-02 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_alter_preferences_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='calorias',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='preferences',
            name='carbohidratos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='preferences',
            name='grasas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='preferences',
            name='proteinas',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='altura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='genero',
            field=models.CharField(choices=[('male', 'Hombre'), ('female', 'Mujer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='nivel_actividad',
            field=models.CharField(choices=[('sedentario', 'Sedentario'), ('ligero', 'Ligero'), ('moderado', 'Moderado'), ('activo', 'Activo'), ('muy_activo', 'Muy Activo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='objetivo',
            field=models.CharField(choices=[('lose_weight', 'Bajar de peso'), ('improve_health', 'Mejorar salud'), ('gain_weight', 'Subir de peso')], max_length=20),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='peso',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='presupuesto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
