# Generated by Django 5.1.5 on 2025-03-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.FloatField(),
        ),
    ]
