# Generated by Django 5.1.6 on 2025-04-23 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_preferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
